from abc import ABC, abstractmethod
from typing import Any, List
from dataclasses import dataclass, field

from shared_kernel.events.base import DomainEvent
from shared_kernel.specifications.base import SpecificationResult, Severity

@dataclass
class PolicyResult:
    """
    Result of a domain policy evaluation.
    Contains any events generated by the policy, along with violations and warnings.
    """
    events: List[DomainEvent] = field(default_factory=list)
    violations: List[SpecificationResult] = field(default_factory=list)
    warnings: List[SpecificationResult] = field(default_factory=list)

    @property
    def is_valid(self) -> bool:
        return len(self.violations) == 0

    def add_event(self, event: DomainEvent) -> None:
        self.events.append(event)

    def add_violation(self, spec_result: SpecificationResult) -> None:
        if spec_result.severity in (Severity.ERROR, Severity.BLOCKING):
            self.violations.append(spec_result)
        else:
            self.add_warning(spec_result)

    def add_warning(self, spec_result: SpecificationResult) -> None:
        self.warnings.append(spec_result)


class DomainPolicy(ABC):
    """
    Base class for Domain Policies.
    Policies encapsulate complex business rules that might span multiple entities,
    invoke specifications, and produce new domain events.
    """
    @abstractmethod
    def evaluate(self, **kwargs: Any) -> PolicyResult:
        pass
