FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

WORKDIR /app
COPY backend/pyproject.toml backend/uv.lock ./
RUN uv sync --frozen --no-install-project

COPY backend/ .

ENV PYTHONPATH=/app

CMD ["uv", "run", "celery", "-A", "apps.api_gateway.src.worker", "worker", "--loglevel=info"]
