FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

WORKDIR /app
COPY backend/pyproject.toml backend/uv.lock ./
RUN uv sync --frozen --no-install-project

COPY backend/apps/api_gateway ./apps/api_gateway
COPY backend/modules ./modules
COPY backend/packages ./packages

ENV PYTHONPATH=/app

CMD ["uv", "run", "celery", "-A", "apps.api_gateway.src.worker", "worker", "--loglevel=info"]
