"""create_commercial_tables

Revision ID: 1efd5969ce2b
Revises: e7b8c9d0a1b2
Create Date: 2026-07-26 00:50:29.699099

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1efd5969ce2b'
down_revision: str | Sequence[str] | None = 'e7b8c9d0a1b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=False),
    sa.Column('corporate_name', sa.String(length=255), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PROSPECT', 'CUSTOMER', 'INACTIVE', 'BLOCKED', name='commercial_company_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_companies_tenant_id'), 'commercial_companies', ['tenant_id'], unique=False)
    op.create_table('commercial_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'LOST', 'CONVERTED', name='commercial_lead_status', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_leads_tenant_id'), 'commercial_leads', ['tenant_id'], unique=False)
    op.create_table('commercial_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['commercial_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_contacts_tenant_id'), 'commercial_contacts', ['tenant_id'], unique=False)
    op.create_table('commercial_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('stage', sa.Enum('DISCOVERY', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', name='commercial_opportunity_stage', native_enum=False), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['commercial_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_opportunities_tenant_id'), 'commercial_opportunities', ['tenant_id'], unique=False)
    op.create_table('commercial_service_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('coordinates', sa.String(length=100), nullable=True),
    sa.Column('operating_hours', sa.String(length=255), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['commercial_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_service_locations_tenant_id'), 'commercial_service_locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    
    # Enable RLS on new tables
    tables = [
        'commercial_companies',
        'commercial_leads',
        'commercial_contacts',
        'commercial_opportunities',
        'commercial_service_locations'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation_policy ON {table}
            USING (
                current_setting('app.current_tenant_id', true) IS NOT NULL
                AND tenant_id = current_setting('app.current_tenant_id')::uuid
            );
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        'commercial_companies',
        'commercial_leads',
        'commercial_contacts',
        'commercial_opportunities',
        'commercial_service_locations'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_commercial_service_locations_tenant_id'), table_name='commercial_service_locations')
    op.drop_table('commercial_service_locations')
    op.drop_index(op.f('ix_commercial_opportunities_tenant_id'), table_name='commercial_opportunities')
    op.drop_table('commercial_opportunities')
    op.drop_index(op.f('ix_commercial_contacts_tenant_id'), table_name='commercial_contacts')
    op.drop_table('commercial_contacts')
    op.drop_index(op.f('ix_commercial_leads_tenant_id'), table_name='commercial_leads')
    op.drop_table('commercial_leads')
    op.drop_index(op.f('ix_commercial_companies_tenant_id'), table_name='commercial_companies')
    op.drop_table('commercial_companies')
    # ### end Alembic commands ###
