"""add geographic fields to commercial lead

Revision ID: 5fa296e7cdf8
Revises: a74c61245600
Create Date: 2026-08-01 05:10:34.384936

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5fa296e7cdf8'
down_revision: str | Sequence[str] | None = 'a74c61245600'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
