"""create routing requirements table

Revision ID: 608d4fd5a554
Revises: a912c3d4e5f6
Create Date: 2026-07-28 21:43:18.538877

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '608d4fd5a554'
down_revision: str | Sequence[str] | None = 'a912c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
