"""add workflow_type and destination_id to service_order

Revision ID: 669ef2cd2338
Revises: 5fa296e7cdf8
Create Date: 2026-08-01 05:22:11.556856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669ef2cd2338'
down_revision: Union[str, Sequence[str], None] = '5fa296e7cdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    workflow_type_enum = sa.Enum('DIRECT_TO_LANDFILL', 'WAREHOUSE_STORAGE', name='serviceorderworkflowtype')
    workflow_type_enum.create(op.get_bind())
    op.add_column('logistics_service_orders', sa.Column('workflow_type', workflow_type_enum, server_default='WAREHOUSE_STORAGE', nullable=False))
    op.add_column('logistics_service_orders', sa.Column('destination_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistics_service_orders', 'destination_id')
    op.drop_column('logistics_service_orders', 'workflow_type')
    workflow_type_enum = sa.Enum('DIRECT_TO_LANDFILL', 'WAREHOUSE_STORAGE', name='serviceorderworkflowtype')
    workflow_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
