"""add billing invoice models

Revision ID: 729bb6207aba
Revises: 669ef2cd2338
Create Date: 2026-08-01 05:34:35.845619

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '729bb6207aba'
down_revision: str | Sequence[str] | None = '669ef2cd2338'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_company_id'), 'billing_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_reference_date'), 'billing_invoices', ['reference_date'], unique=False)
    op.create_index(op.f('ix_billing_invoices_tenant_id'), 'billing_invoices', ['tenant_id'], unique=False)
    op.create_table('billing_invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('service_order_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoice_items_invoice_id'), 'billing_invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_invoice_items_service_order_id'), 'billing_invoice_items', ['service_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_invoice_items_service_order_id'), table_name='billing_invoice_items')
    op.drop_index(op.f('ix_billing_invoice_items_invoice_id'), table_name='billing_invoice_items')
    op.drop_table('billing_invoice_items')
    op.drop_index(op.f('ix_billing_invoices_tenant_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_reference_date'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_company_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    
    invoice_status_enum = sa.Enum('DRAFT', 'ISSUED', 'PAID', 'CANCELLED', name='invoicestatus')
    invoice_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
