"""Add routing models

Revision ID: 7afdd7cc3ae9
Revises: 7e3d0b0ea43a
Create Date: 2026-07-17 03:04:32.212257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afdd7cc3ae9'
down_revision: Union[str, Sequence[str], None] = '7e3d0b0ea43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='routestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_routes_tenant_id'), 'routing_routes', ['tenant_id'], unique=False)
    op.create_table('routing_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routing_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    # --- RLS Commands ---
    op.execute("ALTER TABLE routing_routes ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE routing_routes FORCE ROW LEVEL SECURITY;")
    
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON routing_routes
        AS PERMISSIVE FOR ALL
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # --- RLS Commands ---
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON routing_routes;")
    op.execute("ALTER TABLE routing_routes DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_stops')
    op.drop_index(op.f('ix_routing_routes_tenant_id'), table_name='routing_routes')
    op.drop_table('routing_routes')
    
    from sqlalchemy.dialects import postgresql
    routestatus = postgresql.ENUM('DRAFT', 'PLANNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='routestatus')
    routestatus.drop(op.get_bind())
    # ### end Alembic commands ###
