"""add price_table_id to quotation

Revision ID: 8d16b6b5ad1e
Revises: ea65b8d57ffd
Create Date: 2026-08-13 04:49:35.355024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d16b6b5ad1e'
down_revision: Union[str, Sequence[str], None] = 'ea65b8d57ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
