"""Add route capacity and fleet fields, stop status

Revision ID: 9649bd2daf9e
Revises: 7afdd7cc3ae9
Create Date: 2026-07-17 03:29:58.422372

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9649bd2daf9e'
down_revision: str | Sequence[str] | None = '7afdd7cc3ae9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routing_routes', sa.Column('estimated_volume', sa.Float(), nullable=True))
    op.add_column('routing_routes', sa.Column('estimated_weight', sa.Float(), nullable=True))
    op.add_column('routing_routes', sa.Column('planned_distance', sa.Float(), nullable=True))
    op.add_column('routing_routes', sa.Column('planned_duration', sa.Float(), nullable=True))
    op.add_column('routing_routes', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('routing_routes', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_routing_routes_driver_id'), 'routing_routes', ['driver_id'], unique=False)
    op.create_index(op.f('ix_routing_routes_vehicle_id'), 'routing_routes', ['vehicle_id'], unique=False)
    from sqlalchemy.dialects import postgresql
    stopstatus = postgresql.ENUM('SCHEDULED', 'ARRIVED', 'COLLECTED', 'SKIPPED', name='stopstatus')
    stopstatus.create(op.get_bind())
    op.add_column('routing_stops', sa.Column('status', sa.Enum('SCHEDULED', 'ARRIVED', 'COLLECTED', 'SKIPPED', name='stopstatus'), server_default='SCHEDULED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routing_stops', 'status')
    op.drop_index(op.f('ix_routing_routes_vehicle_id'), table_name='routing_routes')
    op.drop_index(op.f('ix_routing_routes_driver_id'), table_name='routing_routes')
    op.drop_column('routing_routes', 'driver_id')
    op.drop_column('routing_routes', 'vehicle_id')
    op.drop_column('routing_routes', 'planned_duration')
    op.drop_column('routing_routes', 'planned_distance')
    op.drop_column('routing_routes', 'estimated_weight')
    op.drop_column('routing_routes', 'estimated_volume')
    
    from sqlalchemy.dialects import postgresql
    stopstatus = postgresql.ENUM('SCHEDULED', 'ARRIVED', 'COLLECTED', 'SKIPPED', name='stopstatus')
    stopstatus.drop(op.get_bind())
    # ### end Alembic commands ###
