"""Add Waste Manifest table

Revision ID: a74c61245600
Revises: f1123de57b35
Create Date: 2026-08-01 02:45:56.089951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74c61245600'
down_revision: Union[str, Sequence[str], None] = 'f1123de57b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_waste_manifests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('generator_company_id', sa.Uuid(), nullable=False),
    sa.Column('transporter_company_id', sa.Uuid(), nullable=False),
    sa.Column('service_order_id', sa.Uuid(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'RECEIVED', 'CANCELED', name='mtrstatus'), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_waste_manifests_generator_company_id'), 'compliance_waste_manifests', ['generator_company_id'], unique=False)
    op.create_index(op.f('ix_compliance_waste_manifests_issue_date'), 'compliance_waste_manifests', ['issue_date'], unique=False)
    op.create_index(op.f('ix_compliance_waste_manifests_service_order_id'), 'compliance_waste_manifests', ['service_order_id'], unique=False)
    op.create_index(op.f('ix_compliance_waste_manifests_tenant_id'), 'compliance_waste_manifests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_compliance_waste_manifests_transporter_company_id'), 'compliance_waste_manifests', ['transporter_company_id'], unique=False)
    op.create_table('compliance_waste_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manifest_id', sa.Uuid(), nullable=False),
    sa.Column('waste_type', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('un_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['compliance_waste_manifests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_waste_items_manifest_id'), 'compliance_waste_items', ['manifest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_waste_items_manifest_id'), table_name='compliance_waste_items')
    op.drop_table('compliance_waste_items')
    op.drop_index(op.f('ix_compliance_waste_manifests_transporter_company_id'), table_name='compliance_waste_manifests')
    op.drop_index(op.f('ix_compliance_waste_manifests_tenant_id'), table_name='compliance_waste_manifests')
    op.drop_index(op.f('ix_compliance_waste_manifests_service_order_id'), table_name='compliance_waste_manifests')
    op.drop_index(op.f('ix_compliance_waste_manifests_issue_date'), table_name='compliance_waste_manifests')
    op.drop_index(op.f('ix_compliance_waste_manifests_generator_company_id'), table_name='compliance_waste_manifests')
    op.drop_table('compliance_waste_manifests')
    # ### end Alembic commands ###
