"""Add fleet models

Revision ID: a8f9cd91e876
Revises: 9649bd2daf9e
Create Date: 2026-07-17 03:34:01.858366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f9cd91e876'
down_revision: Union[str, Sequence[str], None] = '9649bd2daf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    op.create_table('fleet_drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'OFF_DUTY', name='driverstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_drivers_tenant_id'), 'fleet_drivers', ['tenant_id'], unique=False)
    
    # RLS Driver
    op.execute("ALTER TABLE fleet_drivers ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE fleet_drivers FORCE ROW LEVEL SECURITY;")
    op.execute('''
        CREATE POLICY tenant_isolation_policy ON fleet_drivers 
        USING (tenant_id = current_setting('app.current_tenant_id', TRUE)::uuid);
    ''')
    
    op.create_table('fleet_vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.Enum('COMPACTOR_TRUCK', 'ROLL_OFF_TRUCK', 'VACUUM_TRUCK', 'VAN', name='vehicletype'), nullable=False),
    sa.Column('capacity_volume', sa.Float(), nullable=False),
    sa.Column('capacity_weight', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='vehiclestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_vehicles_tenant_id'), 'fleet_vehicles', ['tenant_id'], unique=False)
    
    # RLS Vehicle
    op.execute("ALTER TABLE fleet_vehicles ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE fleet_vehicles FORCE ROW LEVEL SECURITY;")
    op.execute('''
        CREATE POLICY tenant_isolation_policy ON fleet_vehicles 
        USING (tenant_id = current_setting('app.current_tenant_id', TRUE)::uuid);
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleet_vehicles_tenant_id'), table_name='fleet_vehicles')
    op.drop_table('fleet_vehicles')
    op.drop_index(op.f('ix_fleet_drivers_tenant_id'), table_name='fleet_drivers')
    op.drop_table('fleet_drivers')
    
    from sqlalchemy.dialects import postgresql
    
    driverstatus = postgresql.ENUM('AVAILABLE', 'ASSIGNED', 'OFF_DUTY', name='driverstatus')
    driverstatus.drop(op.get_bind())
    
    vehicletype = postgresql.ENUM('COMPACTOR_TRUCK', 'ROLL_OFF_TRUCK', 'VACUUM_TRUCK', 'VAN', name='vehicletype')
    vehicletype.drop(op.get_bind())
    
    vehiclestatus = postgresql.ENUM('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='vehiclestatus')
    vehiclestatus.drop(op.get_bind())
    # ### end Alembic commands ###
