"""create_catalog_tables

Revision ID: aef0fb973d94
Revises: be504d155496
Create Date: 2026-07-26 01:50:14.295777

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aef0fb973d94'
down_revision: str | Sequence[str] | None = 'be504d155496'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_service_attributes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('attribute_type', sa.Enum('WASTE_TYPE', 'CONTAINER_TYPE', 'FREQUENCY', 'CAPACITY', 'NUMERIC', name='catalog_attribute_type', native_enum=False), nullable=False),
    sa.Column('possible_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_service_attributes_tenant_id'), 'catalog_service_attributes', ['tenant_id'], unique=False)
    op.create_table('catalog_units_of_measure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_type', sa.Enum('VOLUME', 'WEIGHT', 'UNIT', 'DISTANCE', 'TIME', name='catalog_uom_base_type', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_units_of_measure_tenant_id'), 'catalog_units_of_measure', ['tenant_id'], unique=False)
    op.create_table('catalog_service_offerings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='catalog_service_status', native_enum=False), nullable=False),
    sa.Column('default_uom_id', sa.Uuid(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_uom_id'], ['catalog_units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_service_offerings_tenant_id'), 'catalog_service_offerings', ['tenant_id'], unique=False)
    op.create_table('catalog_service_offering_attributes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_offering_id', sa.Uuid(), nullable=False),
    sa.Column('service_attribute_id', sa.Uuid(), nullable=False),
    sa.Column('allowed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_attribute_id'], ['catalog_service_attributes.id'], ),
    sa.ForeignKeyConstraint(['service_offering_id'], ['catalog_service_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_service_offering_attributes_tenant_id'), 'catalog_service_offering_attributes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- RLS Policies (Upgrade) ---
    tables = [
        'catalog_service_attributes',
        'catalog_units_of_measure',
        'catalog_service_offerings',
        'catalog_service_offering_attributes'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"CREATE POLICY tenant_isolation_policy ON {table} "
            f"USING (tenant_id = current_setting('app.current_tenant_id')::uuid);"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # --- RLS Policies (Downgrade) ---
    tables = [
        'catalog_service_attributes',
        'catalog_units_of_measure',
        'catalog_service_offerings',
        'catalog_service_offering_attributes'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_service_offering_attributes_tenant_id'), table_name='catalog_service_offering_attributes')
    op.drop_table('catalog_service_offering_attributes')
    op.drop_index(op.f('ix_catalog_service_offerings_tenant_id'), table_name='catalog_service_offerings')
    op.drop_table('catalog_service_offerings')
    op.drop_index(op.f('ix_catalog_units_of_measure_tenant_id'), table_name='catalog_units_of_measure')
    op.drop_table('catalog_units_of_measure')
    op.drop_index(op.f('ix_catalog_service_attributes_tenant_id'), table_name='catalog_service_attributes')
    op.drop_table('catalog_service_attributes')
    # ### end Alembic commands ###
