"""Add quotations schema

Revision ID: b082ae6f018f
Revises: b700436a06b7
Create Date: 2026-07-26 03:16:14.892794

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b082ae6f018f'
down_revision: str | Sequence[str] | None = 'b700436a06b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations_quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PRICED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'EXPIRED', name='quotationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_quotations_quotations_company_id'), 'quotations_quotations', ['company_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_quotations_quotations_tenant_id'), 'quotations_quotations', ['tenant_id'], unique=False, schema='public')
    op.create_table('quotations_quotation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('service_offering_id', sa.UUID(), nullable=False),
    sa.Column('unit_of_measure_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['public.quotations_quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_quotations_quotation_items_quotation_id'), 'quotations_quotation_items', ['quotation_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_quotations_quotation_items_tenant_id'), 'quotations_quotation_items', ['tenant_id'], unique=False, schema='public')
    op.create_table('quotations_quotation_item_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('quotation_item_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('base_unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_base_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('surcharges_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('discounts_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('pricing_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['public.quotations_quotation_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_quotations_quotation_item_snapshots_quotation_item_id'), 'quotations_quotation_item_snapshots', ['quotation_item_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_quotations_quotation_item_snapshots_tenant_id'), 'quotations_quotation_item_snapshots', ['tenant_id'], unique=False, schema='public')
    # Enable Row Level Security (RLS)
    op.execute('ALTER TABLE public.quotations_quotations ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE public.quotations_quotation_items ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE public.quotations_quotation_item_snapshots ENABLE ROW LEVEL SECURITY')

    # Create policies
    op.execute('''
        CREATE POLICY tenant_isolation_policy ON public.quotations_quotations
        AS PERMISSIVE FOR ALL
        TO public
        USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid)
    ''')
    op.execute('''
        CREATE POLICY tenant_isolation_policy ON public.quotations_quotation_items
        AS PERMISSIVE FOR ALL
        TO public
        USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid)
    ''')
    op.execute('''
        CREATE POLICY tenant_isolation_policy ON public.quotations_quotation_item_snapshots
        AS PERMISSIVE FOR ALL
        TO public
        USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid)
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop policies
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON public.quotations_quotation_item_snapshots')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON public.quotations_quotation_items')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON public.quotations_quotations')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_quotations_quotation_item_snapshots_tenant_id'), table_name='quotations_quotation_item_snapshots', schema='public')
    op.drop_index(op.f('ix_public_quotations_quotation_item_snapshots_quotation_item_id'), table_name='quotations_quotation_item_snapshots', schema='public')
    op.drop_table('quotations_quotation_item_snapshots', schema='public')
    op.drop_index(op.f('ix_public_quotations_quotation_items_tenant_id'), table_name='quotations_quotation_items', schema='public')
    op.drop_index(op.f('ix_public_quotations_quotation_items_quotation_id'), table_name='quotations_quotation_items', schema='public')
    op.drop_table('quotations_quotation_items', schema='public')
    op.drop_index(op.f('ix_public_quotations_quotations_tenant_id'), table_name='quotations_quotations', schema='public')
    op.drop_index(op.f('ix_public_quotations_quotations_company_id'), table_name='quotations_quotations', schema='public')
    op.drop_table('quotations_quotations')
    
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS quotationstatus;")
    # ### end Alembic commands ###
