"""create_pricing_tables

Revision ID: b700436a06b7
Revises: aef0fb973d94
Create Date: 2026-07-26 02:28:41.559127

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b700436a06b7'
down_revision: str | Sequence[str] | None = 'aef0fb973d94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_price_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_price_tables_tenant_id'), 'pricing_price_tables', ['tenant_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('service_offering_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_tenant_id'), 'pricing_rules', ['tenant_id'], unique=False)
    op.create_table('pricing_price_table_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('price_table_id', sa.UUID(), nullable=False),
    sa.Column('service_offering_id', sa.UUID(), nullable=False),
    sa.Column('unit_of_measure_id', sa.UUID(), nullable=False),
    sa.Column('unit_price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['price_table_id'], ['pricing_price_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_price_table_items_tenant_id'), 'pricing_price_table_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    
    # --- RLS Policies for Multi-Tenancy ---
    tables = [
        "pricing_price_tables",
        "pricing_price_table_items",
        "pricing_rules"
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation_policy ON {table}
            USING (tenant_id = current_setting('app.current_tenant_id', TRUE)::uuid);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # --- Drop RLS Policies ---
    tables = [
        "pricing_price_tables",
        "pricing_price_table_items",
        "pricing_rules"
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_price_table_items_tenant_id'), table_name='pricing_price_table_items')
    op.drop_table('pricing_price_table_items')
    op.drop_index(op.f('ix_pricing_rules_tenant_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_pricing_price_tables_tenant_id'), table_name='pricing_price_tables')
    op.drop_table('pricing_price_tables')
    # ### end Alembic commands ###
