"""create_cross_cutting_tables

Revision ID: be504d155496
Revises: 1efd5969ce2b
Create Date: 2026-07-26 01:15:34.110156

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be504d155496'
down_revision: str | Sequence[str] | None = '1efd5969ce2b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_cutting_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_cutting_activities_tenant_id'), 'cross_cutting_activities', ['tenant_id'], unique=False)
    op.create_table('cross_cutting_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_cutting_tags_tenant_id'), 'cross_cutting_tags', ['tenant_id'], unique=False)
    op.create_table('cross_cutting_activity_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['cross_cutting_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_cutting_activity_relations_tenant_id'), 'cross_cutting_activity_relations', ['tenant_id'], unique=False)
    op.create_table('cross_cutting_taggings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['cross_cutting_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_cutting_taggings_tenant_id'), 'cross_cutting_taggings', ['tenant_id'], unique=False)
    
    # Enable RLS
    tables = [
        'cross_cutting_activities',
        'cross_cutting_tags',
        'cross_cutting_activity_relations',
        'cross_cutting_taggings'
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation_policy ON {table}
            USING (
                current_setting('app.current_tenant_id', true) IS NOT NULL
                AND tenant_id = current_setting('app.current_tenant_id')::uuid
            );
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        'cross_cutting_activities',
        'cross_cutting_tags',
        'cross_cutting_activity_relations',
        'cross_cutting_taggings'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_cross_cutting_taggings_tenant_id'), table_name='cross_cutting_taggings')
    op.drop_table('cross_cutting_taggings')
    op.drop_index(op.f('ix_cross_cutting_activity_relations_tenant_id'), table_name='cross_cutting_activity_relations')
    op.drop_table('cross_cutting_activity_relations')
    op.drop_index(op.f('ix_cross_cutting_tags_tenant_id'), table_name='cross_cutting_tags')
    op.drop_table('cross_cutting_tags')
    op.drop_index(op.f('ix_cross_cutting_activities_tenant_id'), table_name='cross_cutting_activities')
    op.drop_table('cross_cutting_activities')
    # ### end Alembic commands ###
