"""add_facilities_destinations

Revision ID: e88bc9a45d7c
Revises: 8d16b6b5ad1e
Create Date: 2026-08-13 07:56:06.042853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88bc9a45d7c'
down_revision: Union[str, Sequence[str], None] = '8d16b6b5ad1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities_destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('DDN_BASE', 'LANDFILL', 'RECYCLING_CENTER', 'TREATMENT_PLANT', 'OTHER', name='destinationtype'), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=False),
    sa.Column('address_number', sa.String(length=50), nullable=False),
    sa.Column('address_complement', sa.String(length=255), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=False),
    sa.Column('address_city', sa.String(length=100), nullable=False),
    sa.Column('address_state', sa.String(length=50), nullable=False),
    sa.Column('address_zip_code', sa.String(length=20), nullable=False),
    sa.Column('address_latitude', sa.String(length=50), nullable=True),
    sa.Column('address_longitude', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_destinations_tenant_id'), 'facilities_destinations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_destinations_tenant_id'), table_name='facilities_destinations')
    op.drop_table('facilities_destinations')
    # ### end Alembic commands ###
