"""add address to commercial lead real

Revision ID: ea65b8d57ffd
Revises: 279533702efe
Create Date: 2026-08-02 15:09:14.733436

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea65b8d57ffd'
down_revision: str | Sequence[str] | None = '729bb6207aba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_leads', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('commercial_leads', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('commercial_leads', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commercial_leads', 'longitude')
    op.drop_column('commercial_leads', 'latitude')
    op.drop_column('commercial_leads', 'address')
    # ### end Alembic commands ###
