"""Add Service Orders table

Revision ID: f1123de57b35
Revises: 608d4fd5a554
Create Date: 2026-08-01 02:38:08.955293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1123de57b35'
down_revision: Union[str, Sequence[str], None] = '608d4fd5a554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_service_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('service_plan_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='serviceorderstatus'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_service_orders_company_id'), 'logistics_service_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_logistics_service_orders_scheduled_date'), 'logistics_service_orders', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_logistics_service_orders_service_plan_id'), 'logistics_service_orders', ['service_plan_id'], unique=False)
    op.create_index(op.f('ix_logistics_service_orders_tenant_id'), 'logistics_service_orders', ['tenant_id'], unique=False)
    op.create_table('logistics_service_order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_order_id', sa.Uuid(), nullable=False),
    sa.Column('service_offering_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['logistics_service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_service_order_items_service_order_id'), 'logistics_service_order_items', ['service_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistics_service_order_items_service_order_id'), table_name='logistics_service_order_items')
    op.drop_table('logistics_service_order_items')
    op.drop_index(op.f('ix_logistics_service_orders_tenant_id'), table_name='logistics_service_orders')
    op.drop_index(op.f('ix_logistics_service_orders_service_plan_id'), table_name='logistics_service_orders')
    op.drop_index(op.f('ix_logistics_service_orders_scheduled_date'), table_name='logistics_service_orders')
    op.drop_index(op.f('ix_logistics_service_orders_company_id'), table_name='logistics_service_orders')
    op.drop_table('logistics_service_orders')
    # ### end Alembic commands ###
