"""create contracts tables

Revision ID: f401d42e98ed
Revises: b082ae6f018f
Create Date: 2026-07-26 03:59:12.826381

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f401d42e98ed'
down_revision: str | Sequence[str] | None = 'b082ae6f018f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'WAITING_SIGNATURE', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'CANCELLED', name='contractstatus'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('renewal_rule', sa.String(), nullable=True),
    sa.Column('adjustment_rule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contracts_company_id'), 'contracts_contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contracts_contracts_quotation_id'), 'contracts_contracts', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_contracts_contracts_tenant_id'), 'contracts_contracts', ['tenant_id'], unique=False)
    op.create_table('contracts_contract_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_versions_contract_id'), 'contracts_contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contracts_contract_versions_tenant_id'), 'contracts_contract_versions', ['tenant_id'], unique=False)
    op.create_table('contracts_contract_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('service_offering_id', sa.UUID(), nullable=False),
    sa.Column('unit_of_measure_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['contracts_contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_items_tenant_id'), 'contracts_contract_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contracts_contract_items_version_id'), 'contracts_contract_items', ['version_id'], unique=False)
    op.create_table('contracts_contract_item_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_item_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('base_unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_base_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('surcharges_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('discounts_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('pricing_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contracts_contract_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_item_snapshots_contract_item_id'), 'contracts_contract_item_snapshots', ['contract_item_id'], unique=True)
    op.create_index(op.f('ix_contracts_contract_item_snapshots_tenant_id'), 'contracts_contract_item_snapshots', ['tenant_id'], unique=False)
    
    # RLS Policies
    op.execute("ALTER TABLE contracts_contracts ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON contracts_contracts USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    
    op.execute("ALTER TABLE contracts_contract_versions ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON contracts_contract_versions USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    
    op.execute("ALTER TABLE contracts_contract_items ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON contracts_contract_items USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    
    op.execute("ALTER TABLE contracts_contract_item_snapshots ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON contracts_contract_item_snapshots USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")

    op.drop_index(op.f('ix_public_quotations_quotation_item_snapshots_quotation_item_id'), table_name='quotations_quotation_item_snapshots')
    op.drop_index(op.f('ix_public_quotations_quotation_item_snapshots_tenant_id'), table_name='quotations_quotation_item_snapshots')
    op.create_index(op.f('ix_quotations_quotation_item_snapshots_quotation_item_id'), 'quotations_quotation_item_snapshots', ['quotation_item_id'], unique=True)
    op.create_index(op.f('ix_quotations_quotation_item_snapshots_tenant_id'), 'quotations_quotation_item_snapshots', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_public_quotations_quotation_items_quotation_id'), table_name='quotations_quotation_items')
    op.drop_index(op.f('ix_public_quotations_quotation_items_tenant_id'), table_name='quotations_quotation_items')
    op.create_index(op.f('ix_quotations_quotation_items_quotation_id'), 'quotations_quotation_items', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_items_tenant_id'), 'quotations_quotation_items', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_public_quotations_quotations_company_id'), table_name='quotations_quotations')
    op.drop_index(op.f('ix_public_quotations_quotations_tenant_id'), table_name='quotations_quotations')
    op.create_index(op.f('ix_quotations_quotations_company_id'), 'quotations_quotations', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotations_tenant_id'), 'quotations_quotations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_quotations_tenant_id'), table_name='quotations_quotations')
    op.drop_index(op.f('ix_quotations_quotations_company_id'), table_name='quotations_quotations')
    op.create_index(op.f('ix_public_quotations_quotations_tenant_id'), 'quotations_quotations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_public_quotations_quotations_company_id'), 'quotations_quotations', ['company_id'], unique=False)
    op.drop_index(op.f('ix_quotations_quotation_items_tenant_id'), table_name='quotations_quotation_items')
    op.drop_index(op.f('ix_quotations_quotation_items_quotation_id'), table_name='quotations_quotation_items')
    op.create_index(op.f('ix_public_quotations_quotation_items_tenant_id'), 'quotations_quotation_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_public_quotations_quotation_items_quotation_id'), 'quotations_quotation_items', ['quotation_id'], unique=False)
    op.drop_index(op.f('ix_quotations_quotation_item_snapshots_tenant_id'), table_name='quotations_quotation_item_snapshots')
    op.drop_index(op.f('ix_quotations_quotation_item_snapshots_quotation_item_id'), table_name='quotations_quotation_item_snapshots')
    op.create_index(op.f('ix_public_quotations_quotation_item_snapshots_tenant_id'), 'quotations_quotation_item_snapshots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_public_quotations_quotation_item_snapshots_quotation_item_id'), 'quotations_quotation_item_snapshots', ['quotation_item_id'], unique=True)
    op.drop_index(op.f('ix_contracts_contract_item_snapshots_tenant_id'), table_name='contracts_contract_item_snapshots')
    op.drop_index(op.f('ix_contracts_contract_item_snapshots_contract_item_id'), table_name='contracts_contract_item_snapshots')
    op.drop_table('contracts_contract_item_snapshots')
    op.drop_index(op.f('ix_contracts_contract_items_version_id'), table_name='contracts_contract_items')
    op.drop_index(op.f('ix_contracts_contract_items_tenant_id'), table_name='contracts_contract_items')
    op.drop_table('contracts_contract_items')
    op.drop_index(op.f('ix_contracts_contract_versions_tenant_id'), table_name='contracts_contract_versions')
    op.drop_index(op.f('ix_contracts_contract_versions_contract_id'), table_name='contracts_contract_versions')
    op.drop_table('contracts_contract_versions')
    op.drop_index(op.f('ix_contracts_contracts_tenant_id'), table_name='contracts_contracts')
    op.drop_index(op.f('ix_contracts_contracts_quotation_id'), table_name='contracts_contracts')
    op.drop_index(op.f('ix_contracts_contracts_company_id'), table_name='contracts_contracts')
    op.drop_table('contracts_contracts')
    
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS contractstatus;")
    # ### end Alembic commands ###
